# t-SNE
### (Dimensional Reduction Approach) It only used for visualization purpose

- We get more data points in tail region bcz of that we use t distribution

- It calculates the probability between datapoint in High dimensional subspace and Low dimnesional subspace and Aim is to match these probabilities.

- P(j!i) Probability of i that i record will pick the j record as its neighbor 

- It should match Low dimensional data to Hogh dimensional data. 
- If it is matching then move forward with the data visaulizaton.

- KL Divergence = measure of how different one probability distribution from a second

- Gradient Descent = Change the data point  in Lower dimensional subspace, unless and untill KL values is minimum 

- Gradient Descent = It is keep on changing the values unless and until it will reaches the minium KL values

- tsne is unsupervised approach
- For PSA and t-SNE is DR approach no need of target column

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r"C:\Users\sunny\Desktop\DS Material\Data Set\Wine.csv")
df.head()

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline,Customer_Segment
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065,1
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050,1
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185,1
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480,1
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735,1

In [3]:
!pip install bioinfokit

Requirement already satisfied: bioinfokit in c:\users\sunny\anaconda3\lib\site-packages (2.1.0)
Requirement already satisfied: matplotlib in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (3.5.2)
Requirement already satisfied: scipy in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (1.9.1)
Requirement already satisfied: matplotlib-venn in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (0.11.7)
Requirement already satisfied: tabulate in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (0.8.10)
Requirement already satisfied: scikit-learn in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (1.0.2)
Requirement already satisfied: textwrap3 in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (0.9.2)
Requirement already satisfied: pandas in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (1.4.4)
Requirement already satisfied: seaborn in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (0.11.2)
Requirement already satisfied: numpy in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (1.21.5)
Requirement already satisfied: statsmodels in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (0.13.2)
Requirement already satisfied: adjustText in c:\users\sunny\anaconda3\lib\site-packages (from bioinfokit) (0.7.3)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (1.4.2)
Requirement already satisfied: cycler>=0.10 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (9.2.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (4.25.0)
Requirement already satisfied: packaging>=20.0 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\sunny\anaconda3\lib\site-packages (from matplotlib->bioinfokit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\sunny\anaconda3\lib\site-packages (from pandas->bioinfokit) (2023.3)
Requirement already satisfied: joblib>=0.11 in c:\users\sunny\anaconda3\lib\site-packages (from scikit-learn->bioinfokit) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sunny\anaconda3\lib\site-packages (from scikit-learn->bioinfokit) (2.2.0)
Requirement already satisfied: patsy>=0.5.2 in c:\users\sunny\anaconda3\lib\site-packages (from statsmodels->bioinfokit) (0.5.2)
Requirement already satisfied: six in c:\users\sunny\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels->bioinfokit) (1.16.0)

In [4]:
from sklearn.manifold import TSNE
from bioinfokit.visuz import cluster

In [5]:
x = df.iloc[:,:-1]
x

,Alcohol,Malic_Acid,Ash,Ash_Alcanity,Magnesium,Total_Phenols,Flavanoids,Nonflavanoid_Phenols,Proanthocyanins,Color_Intensity,Hue,OD280,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [6]:
tsne = TSNE(n_components=2) 
# n_components is 2 = 2 columns
score = tsne.fit_transform(x)
# fit= will calu=culate the probability, distance 
# transform = will replace the values
score

array([[ 6.08278751e+00,  6.14053345e+00],
       [ 6.34158278e+00,  5.41571951e+00],
       [ 7.87044048e+00,  7.38672495e+00],
       [ 9.93239117e+00,  9.23833656e+00],
       [ 3.86487365e-01, -1.24249138e-01],
       [ 9.61779404e+00,  9.32345009e+00],
       [ 9.08352470e+00,  8.19603443e+00],
       [ 8.69310856e+00,  8.69682980e+00],
       [ 6.25562096e+00,  5.32806969e+00],
       [ 5.82474852e+00,  5.74780130e+00],
       [ 9.94481087e+00,  9.44596767e+00],
       [ 8.51170254e+00,  8.49314690e+00],
       [ 9.25706863e+00,  8.48955536e+00],
       [ 7.48367262e+00,  6.94119740e+00],
       [ 1.00147696e+01,  9.57090569e+00],
       [ 8.93679523e+00,  8.70466805e+00],
       [ 8.92412376e+00,  8.09679794e+00],
       [ 7.15049171e+00,  6.72385406e+00],
       [ 1.01423445e+01,  9.77872658e+00],
       [ 2.59022760e+00,  2.24595356e+00],
       [ 1.36977792e+00,  8.81196320e-01],
       [ 1.29739356e+00,  4.64029789e-01],
       [ 5.68422985e+00,  5.56616306e+00],
       [ 5.65982008e+00,  5.06602287e+00],
       [ 2.88943481e+00,  2.01580095e+00],
       [ 2.35256600e+00,  1.84359109e+00],
       [ 8.00916672e+00,  7.48874283e+00],
       [ 8.57989883e+00,  8.56661701e+00],
       [ 3.78614402e+00,  3.26172113e+00],
       [ 6.07201529e+00,  5.18952322e+00],
       [ 9.01789761e+00,  8.13813877e+00],
       [ 9.94220543e+00,  9.47813225e+00],
       [ 5.26885748e+00,  4.80068827e+00],
       [ 8.22309780e+00,  8.00380898e+00],
       [ 6.60218287e+00,  6.38761616e+00],
       [ 3.86960459e+00,  3.33805180e+00],
       [ 3.16152263e+00,  2.75877881e+00],
       [ 6.98207998e+00,  6.25950289e+00],
       [ 5.74214172e+00,  5.11415386e+00],
       [ 9.02410924e-01,  5.31677246e-01],
       [ 1.75449026e+00,  1.16823566e+00],
       [ 5.68007708e+00,  5.57657433e+00],
       [ 6.88613510e+00,  6.09725428e+00],
       [-8.69725466e-01, -2.24310637e+00],
       [ 3.31460047e+00,  2.78224039e+00],
       [ 6.44718504e+00,  6.16819763e+00],
       [ 6.54517508e+00,  5.68938160e+00],
       [ 5.21179295e+00,  4.71326542e+00],
       [ 6.46829557e+00,  5.61706257e+00],
       [ 8.37761784e+00,  8.23677158e+00],
       [ 7.45643902e+00,  6.93942213e+00],
       [ 8.77501774e+00,  7.93545055e+00],
       [ 7.93110180e+00,  7.45771074e+00],
       [ 9.41829681e+00,  8.87767982e+00],
       [ 6.03921318e+00,  6.02611256e+00],
       [ 6.97926188e+00,  6.63917780e+00],
       [ 4.89464474e+00,  4.39366198e+00],
       [ 8.83065033e+00,  7.96465206e+00],
       [ 8.57843685e+00,  8.56041527e+00],
       [-6.71497869e+00, -8.88607502e+00],
       [-9.13703680e-01, -2.22410393e+00],
       [-9.69780064e+00, -1.14770432e+01],
       [-2.78031993e+00, -4.04598379e+00],
       [-1.06733246e+01, -1.25286455e+01],
       [-1.18290930e+01, -1.42860994e+01],
       [-1.25237405e+00, -2.17846918e+00],
       [-7.30750322e+00, -9.73306942e+00],
       [-7.05449152e+00, -9.45504856e+00],
       [ 8.21530282e-01,  8.74957293e-02],
       [-1.96591735e-01,  9.38888937e-02],
       [ 3.07048965e+00,  2.54369354e+00],
       [-1.08279104e+01, -1.29562798e+01],
       [-8.66024208e+00, -1.06949053e+01],
       [ 5.05526733e+00,  4.63948154e+00],
       [ 3.35263920e+00,  2.78743100e+00],
       [-1.03375568e+01, -1.22813826e+01],
       [-1.12816133e+01, -1.33302975e+01],
       [-8.18035507e+00, -9.07510757e+00],
       [ 5.83774149e-01,  4.45241928e-01],
       [-9.24205303e+00, -1.09707479e+01],
       [-1.29290962e+01, -1.47400093e+01],
       [-1.02620497e-01, -1.08597910e+00],
       [-2.47307491e+00, -4.30044174e+00],
       [-7.04430151e+00, -9.08727551e+00],
       [-7.05716848e+00, -8.56676388e+00],
       [-9.69530010e+00, -1.14834213e+01],
       [-7.91160488e+00, -9.66705608e+00],
       [-5.16012812e+00, -6.92165136e+00],
       [-1.46695280e+00, -1.90835345e+00],
       [-2.53243780e+00, -4.62584066e+00],
       [-8.20951271e+00, -1.04560347e+01],
       [-9.62038517e+00, -1.15756836e+01],
       [-7.62834358e+00, -9.92495060e+00],
       [-1.28643513e+01, -1.46628885e+01],
       [-1.20960417e+01, -1.43184538e+01],
       [ 4.28936911e+00,  3.81008315e+00],
       [-3.71797347e+00, -3.74834108e+00],
       [-1.05669937e+01, -1.21900177e+01],
       [-1.73760533e+00, -2.95056343e+00],
       [-1.09310551e+01, -1.30493717e+01],
       [-2.57517517e-01, -1.11330783e+00],
       [-5.16511822e+00, -6.92797565e+00],
       [-1.00795469e+01, -1.19372940e+01],
       [-1.08336630e+01, -1.26696644e+01],
       [-1.64387679e+00, -2.32703805e+00],
       [-1.24992676e+01, -1.46571121e+01],
       [-7.10577011e+00, -9.40519142e+00],
       [-7.99984217e+00, -1.01039543e+01],
       [-1.25151005e+01, -1.46990738e+01],
       [-1.29250419e+00, -1.97521079e+00],
       [-5.53132343e+00, -6.68397617e+00],
       [-1.26305008e+01, -1.42770329e+01],
       [-3.73617887e+00, -4.87209702e+00],
       [-1.02796602e+01, -1.20356588e+01],
       [-1.16418848e+01, -1.32876987e+01],
       [-1.11334944e+01, -1.28266411e+01],
       [-7.79797125e+00, -9.76210785e+00],
       [-1.19706984e+01, -1.44903345e+01],
       [-1.19786463e+01, -1.35162201e+01],
       [-5.07950592e+00, -6.80523586e+00],
       [-3.05525661e+00, -4.24302292e+00],
       [-9.48390865e+00, -1.05780897e+01],
       [-1.16538763e+01, -1.41141310e+01],
       [-1.14465942e+01, -1.36718216e+01],
       [-1.17651567e+01, -1.33715897e+01],
       [-1.15856752e+01, -1.36271143e+01],
       [-1.22768383e+01, -1.38970041e+01],
       [-9.00111866e+00, -1.09219780e+01],
       [-1.24208622e+01, -1.40472212e+01],
       [-4.60655260e+00, -6.21719313e+00],
       [-3.39604855e+00, -3.67509103e+00],
       [-6.58486700e+00, -8.08989811e+00],
       [-5.47160053e+00, -6.90158606e+00],
       [-3.99140310e+00, -5.17419386e+00],
       [-2.01754785e+00, -3.41048145e+00],
       [-6.77592099e-01, -1.56736660e+00],
       [ 1.06234774e-01, -9.01867211e-01],
       [-7.39300108e+00, -8.70810509e+00],
       [-4.66655731e+00, -6.16515827e+00],
       [-4.33690405e+00, -5.67301559e+00],
       [-3.89223385e+00, -5.28546715e+00],
       [ 1.54523981e+00,  6.59575701e-01],
       [-7.14222908e+00, -8.47716618e+00],
       [-5.73568344e+00, -7.41681051e+00],
       [ 2.84036851e+00,  2.32507133e+00],
       [ 2.48364973e+00,  1.75585508e+00],
       [-1.10277624e+01, -1.25400209e+01],
       [-2.82685924e+00, -4.41517210e+00],
       [-2.13786888e+00, -3.29280591e+00],
       [-5.92551231e+00, -7.25978088e+00],
       [-8.42253780e+00, -8.95544815e+00],
       [-8.90057659e+00, -9.95330811e+00],
       [-1.00584440e+01, -1.25702143e+01],
       [-1.20642507e+00, -2.48384714e+00],
       [-2.62293172e+00, -3.55253053e+00],
       [ 2.55946517e-01, -7.56287575e-01],
       [-8.42635536e+00, -1.03212166e+01],
       [ 3.29160547e+00,  2.63974380e+00],
       [-1.88990188e+00, -2.80631471e+00],
       [-3.09255123e+00, -4.58474207e+00],
       [-6.85730362e+00, -8.77178478e+00],
       [-7.95857131e-01, -2.27253628e+00],
       [-5.15370941e+00, -6.37524652e+00],
       [-1.04161644e+00, -2.54944134e+00],
       [-3.29781413e+00, -4.73751259e+00],
       [-6.86620188e+00, -8.75982475e+00],
       [-5.13357580e-01, -1.60852969e+00],
       [-1.13094819e+00, -1.74060595e+00],
       [ 8.84497106e-01, -1.21386945e-02],
       [-3.19072223e+00, -3.79721069e+00],
       [-7.54216433e+00, -8.95193386e+00],
       [-8.70707417e+00, -1.07982225e+01],
       [-1.77874684e+00, -2.90222311e+00],
       [ 6.74492002e-01, -4.02091235e-01],
       [ 9.01557684e-01, -5.51465079e-02],
       [ 2.46260142e+00,  1.94239116e+00],
       [ 2.51295233e+00,  2.11211061e+00],
       [-5.45135069e+00, -6.92503071e+00]], dtype=float32)

In [9]:
cluster.tsneplot(score, colorlist= df['Customer_Segment'])
# It is saved in current working directory

# Diabities dataset

In [10]:
df1 = pd.read_csv(r"C:\Users\sunny\Desktop\DS Material\Data Set\diabetes.csv")
df1.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
tsne = TSNE(n_components=2)
model = tsne.fit_transform(df1.iloc[:,:-1])
model

array([[  3.3187985, -37.157017 ],
       [  4.861649 , -18.287127 ],
       [ -3.7481916, -45.10908  ],
       ...,
       [  9.203651 ,  25.895136 ],
       [ -9.391772 , -31.785248 ],
       [  5.9387035, -19.762756 ]], dtype=float32)

In [12]:
cluster.tsneplot(model, colorlist= df1['Outcome'])

#  iris  Dataset

In [13]:
df2 = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header= None)
df2.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [14]:
tsne = TSNE(n_components=2)
iris = tsne.fit_transform(df2.iloc[:,:-1])
iris

array([[ 10.149618  ,  23.171192  ],
       [  9.234138  ,  20.457317  ],
       [ 10.441611  ,  20.739815  ],
       [ 10.07174   ,  20.245392  ],
       [ 10.399851  ,  23.24962   ],
       [  9.5135355 ,  25.27967   ],
       [ 10.825041  ,  20.960932  ],
       [  9.716958  ,  22.481955  ],
       [ 10.205839  ,  19.494493  ],
       [  9.424741  ,  21.076178  ],
       [ 10.169136  ,  24.646933  ],
       [  9.367702  ,  21.859901  ],
       [  9.543603  ,  20.260895  ],
       [ 10.834516  ,  19.456007  ],
       [ 10.829413  ,  25.72867   ],
       [ 10.331618  ,  26.135948  ],
       [ 10.538406  ,  25.131102  ],
       [  9.944322  ,  23.2304    ],
       [  9.608735  ,  25.64686   ],
       [  9.855076  ,  24.385038  ],
       [  8.904685  ,  24.00914   ],
       [  9.686983  ,  24.042574  ],
       [ 11.58585   ,  21.231117  ],
       [  8.5879    ,  22.87524   ],
       [  8.428366  ,  21.896864  ],
       [  8.785217  ,  20.922226  ],
       [  9.048677  ,  22.738781  ],
       [  9.784012  ,  23.55398   ],
       [  9.950374  ,  23.154095  ],
       [  9.894449  ,  20.926508  ],
       [  9.243424  ,  20.820604  ],
       [  9.130461  ,  23.861713  ],
       [ 10.097112  ,  25.377653  ],
       [ 10.386192  ,  25.782587  ],
       [  9.424741  ,  21.076176  ],
       [ 10.412352  ,  21.726074  ],
       [ 10.78719   ,  24.256197  ],
       [  9.424741  ,  21.076178  ],
       [ 10.500529  ,  19.656055  ],
       [  9.674455  ,  22.827864  ],
       [ 10.45188   ,  22.787521  ],
       [  9.677886  ,  18.948076  ],
       [ 10.884576  ,  20.063227  ],
       [  8.637296  ,  23.217356  ],
       [  8.823237  ,  24.832512  ],
       [  9.546929  ,  20.244291  ],
       [  9.609787  ,  24.539787  ],
       [ 10.433562  ,  20.485937  ],
       [ 10.101109  ,  24.402323  ],
       [  9.951093  ,  22.104866  ],
       [ -1.4311451 ,  -9.450477  ],
       [ -2.7426357 ,  -8.451825  ],
       [ -1.6417456 ,  -9.935542  ],
       [ -4.986399  ,  -3.9125817 ],
       [ -2.6066542 ,  -8.903506  ],
       [ -4.7056503 ,  -6.1413813 ],
       [ -3.2303023 ,  -9.022201  ],
       [ -4.9202385 ,  -2.3762045 ],
       [ -2.155165  ,  -8.745114  ],
       [ -5.3980603 ,  -4.0105357 ],
       [ -5.1412487 ,  -2.569958  ],
       [ -3.9271722 ,  -6.236461  ],
       [ -3.362341  ,  -3.9871802 ],
       [ -3.9092278 ,  -8.1623745 ],
       [ -3.9658918 ,  -3.670414  ],
       [ -1.8785567 ,  -8.572847  ],
       [ -4.9370766 ,  -6.345612  ],
       [ -3.8807352 ,  -4.70333   ],
       [ -5.5826626 ,  -8.220477  ],
       [ -4.4310026 ,  -3.9433255 ],
       [ -4.2763557 ,  -9.558117  ],
       [ -3.3921118 ,  -5.5322714 ],
       [ -4.8965645 ,  -9.518116  ],
       [ -4.010188  ,  -7.810913  ],
       [ -2.6744378 ,  -7.6159415 ],
       [ -2.1537921 ,  -8.363588  ],
       [ -1.8977295 ,  -9.587186  ],
       [ -2.1495283 , -10.727189  ],
       [ -3.980539  ,  -7.4312286 ],
       [ -4.0687356 ,  -3.2214267 ],
       [ -4.6465797 ,  -3.541022  ],
       [ -4.546805  ,  -3.2924762 ],
       [ -4.0041637 ,  -4.4432282 ],
       [ -4.5991893 , -10.758186  ],
       [ -5.3421073 ,  -6.0125656 ],
       [ -3.7401116 ,  -8.52965   ],
       [ -1.9606667 ,  -9.331356  ],
       [ -5.451358  ,  -7.946626  ],
       [ -4.510716  ,  -5.288518  ],
       [ -4.8674235 ,  -4.20304   ],
       [ -5.202729  ,  -5.0897107 ],
       [ -3.6883838 ,  -7.909303  ],
       [ -4.0985446 ,  -4.4945927 ],
       [ -4.9032884 ,  -2.4298618 ],
       [ -4.7880692 ,  -4.971301  ],
       [ -4.268863  ,  -5.5395274 ],
       [ -4.3857    ,  -5.502065  ],
       [ -3.2695985 ,  -7.071196  ],
       [ -4.7581153 ,  -2.2469163 ],
       [ -4.3389893 ,  -5.0394206 ],
       [ -3.7822225 , -15.97406   ],
       [ -5.3005857 , -11.033444  ],
       [ -1.8380364 , -15.953782  ],
       [ -2.6631591 , -13.259768  ],
       [ -2.5303097 , -14.868953  ],
       [ -1.0905355 , -17.182632  ],
       [ -6.2731395 ,  -5.089143  ],
       [ -1.0514673 , -16.500048  ],
       [ -1.59332   , -14.255964  ],
       [ -2.3852303 , -16.89173   ],
       [ -3.8188763 , -13.550182  ],
       [ -3.2840142 , -12.68882   ],
       [ -2.7022715 , -14.783276  ],
       [ -5.7228966 , -10.992972  ],
       [ -5.681544  , -11.759737  ],
       [ -3.9346557 , -14.480611  ],
       [ -2.750816  , -13.521033  ],
       [ -1.6856658 , -17.645563  ],
       [ -0.72577953, -17.338615  ],
       [ -5.6863036 ,  -9.543186  ],
       [ -2.6573887 , -15.709618  ],
       [ -5.7390146 , -10.859101  ],
       [ -0.86920685, -17.203438  ],
       [ -3.9276984 , -10.740994  ],
       [ -2.7848444 , -15.405967  ],
       [ -1.4409009 , -16.142237  ],
       [ -4.048359  , -10.2818575 ],
       [ -4.2226615 , -10.231267  ],
       [ -2.5690517 , -13.975319  ],
       [ -1.1811674 , -15.771763  ],
       [ -1.0977229 , -16.41187   ],
       [ -1.688437  , -17.628826  ],
       [ -2.625276  , -14.149296  ],
       [ -3.5185878 , -10.817064  ],
       [ -3.238904  , -11.977323  ],
       [ -1.401405  , -16.964794  ],
       [ -4.0317674 , -15.368268  ],
       [ -2.8585148 , -13.453681  ],
       [ -4.32852   ,  -9.917206  ],
       [ -2.9150257 , -14.873868  ],
       [ -3.162628  , -15.3031645 ],
       [ -3.6076987 , -14.534338  ],
       [ -5.302407  , -11.0287695 ],
       [ -2.6512663 , -15.913349  ],
       [ -3.2805848 , -15.796576  ],
       [ -3.5449069 , -14.396495  ],
       [ -4.143615  , -11.306321  ],
       [ -3.5231485 , -13.466617  ],
       [ -4.3278475 , -14.907904  ],
       [ -4.831739  , -10.758566  ]], dtype=float32)

In [15]:
cluster.tsneplot(iris, colorlist= df2[4], figname= 'iris_data')